### ISSUE TITLE
Refactor HeroSection component and styles

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#416]
There is some cleanup we should do for the `HeroSection` styling. If you are going to work on this issue, please make sure to address all of the following changes mentioned below. 

Here are the files we will be changing 
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/components/HeroSection.tsx
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/stylesheets/HeroSection.css

## Remove inline styles from  `HeroSection` component
On line 15, we have this ` <strong style={{ fontSize: "2rem" }}>`
Let's remove that inline style and have this instead `<strong className="question-count">`

Then in the `HeroSection` stylesheet add those font size styles to the `question-count` class
```css
.question-count {
  font-size: 2rem;
}
```

## Remove repetition for flex properties
Inside the `HeroSection` stylesheet, we have some repetition of flex properties in the hero-container and hero-content classes.
Here are the properties that being repeated.
```css
  display: flex;
  align-items: center;
  justify-content: center;
```
Please refactor it to this result which will remove that repetition. 

```css
.hero-container,
.hero-content {
  display: flex;
  align-items: center;
  justify-content: center;
}

.hero-container {
  background-image: url("../images/background.webp");
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
  height: 100vh;
  width: 100%;
  box-shadow: inset 0 0 0 1000px rgb(34 27 49 / 57%);
  object-fit: contain;
}

.hero-content {
  width: 800px;
  flex-wrap: wrap;
}
```

## Fix media query and font size inconsistencies  
Right now we are using both min and max widths for the media queries in the `HeroSection` stylesheet.
I think we should be following a mobile first design approach. We should also be consistent and replace all `px` values with `rem` values. 

Please refactor the `hero-text` styles and media queries to this result below

```css
.hero-text h1 {
  font-weight: bold;
  font-size: 2.1rem;
}

.hero-text h2 {
  font-size: 1.5rem;
}

@media screen and (min-width: 768px) {
  .hero-text h1 {
    font-size: 3.1rem;
  }

  .hero-text h2 {
    font-size: 1.8rem;
  }
}

@media screen and (min-width: 1000px) {
  .hero-text h1 {
    font-size: 3.75rem;
  }
}
```
## Guidelines for working on this issue

- This issue will be assigned to `first-timers-only` to the Developer Quiz Site repo
- This issue will be assigned on a first come basis. If you are interested in working on this, please comment below
- Please make sure to read through the [Contributing documentation](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md)
- Please make sure to test these changes locally before submitting a PR
